title: "Sijia Zou, Ph.D."
author: "Sijia Zou"
description: "Sijia Zou, Ph.D."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home",icon:home} #icon: "home"
  - {file: "Research Interest.md", title: "Research Interest", icon: book}
  - {file: "Publications.md", title: "Publications", icon: book}
  - {file: "Contacts&links.md", title: "Contacts", icon: address-book}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
